# Generated by Django 3.1.5 on 2021-01-26 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=50)),
                ('last_name', models.CharField(max_length=50)),
                ('profession', models.CharField(max_length=50)),
                ('yoe', models.DecimalField(decimal_places=1, max_digits=3)),
                ('level', models.CharField(max_length=12)),
            ],
        ),
    ]
