# Generated by Django 3.1.5 on 2021-01-26 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210126_1227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='level',
            field=models.CharField(blank=True, max_length=12),
        ),
        migrations.AlterField(
            model_name='user',
            name='yoe',
            field=models.DecimalField(blank=True, decimal_places=1, max_digits=3),
        ),
    ]
