# Generated by Django 3.1.5 on 2021-01-27 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20210126_1230'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(default='example@email.com', max_length=80),
            preserve_default=False,
        ),
    ]
